# Generated by Django 5.2.3 on 2025-07-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_date',
            field=models.DateField(default=None, null=True, blank=True),
        ),
    ]
