# Generated by Django 5.2.3 on 2025-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_edited_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
