# Generated by Django 5.2.3 on 2025-07-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comment_edited_date_comment_likers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edited_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likers',
        ),
    ]
